/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminHeader: typeof import('./components/AdminHeader.vue')['default']
    Advices: typeof import('./components/Advices.vue')['default']
    Banner: typeof import('./components/Banner.vue')['default']
    Features: typeof import('./components/Features.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HomeDesigns: typeof import('./components/HomeDesigns.vue')['default']
    Products: typeof import('./components/Products.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheButton: typeof import('./components/TheButton.vue')['default']
    TheButtonGroup: typeof import('./components/TheButtonGroup.vue')['default']
    TheCheckbox: typeof import('./components/TheCheckbox.vue')['default']
    TheIconButton: typeof import('./components/TheIconButton.vue')['default']
    TheModal: typeof import('./components/TheModal.vue')['default']
    TheOverlay: typeof import('./components/TheOverlay.vue')['default']
    TheProductCard: typeof import('./components/TheProductCard.vue')['default']
    TheRadio: typeof import('./components/TheRadio.vue')['default']
    TheTable: typeof import('./components/TheTable.vue')['default']
  }
}
